version: '3.3'
services:
  web-server:
    image: harsh530/nginx-webserver:latest
    container_name: web-server
    ports:
      - '3000:3000'
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true